import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import "../globals.css";
import React from "react";


export const metadata = {
    title: "Auth",
    description: "Generated by create next app",
  };

  // how to import fonts from google fonts in nextjs
  const inter = Inter({ subsets: ["latin"] });


  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
    return (
      <ClerkProvider
        // appearance={{
        //   baseTheme: dark,
        // }}
      >
        <html lang='en'>
          <body className={`${inter.className} bg-dark-1`}>{children}</body>
        </html>
      </ClerkProvider>
    );
  }